// Generated by Wrangler on Fri Oct 25 2024 14:14:13 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  DRIZZLE_KIT_CONNECTION_STRING: string;
  SUPABASE_SERVICE_KEY: string;
  DB: Hyperdrive;
}
