name = "office-days"
pages_build_output_dir = "build/client"
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

logpush = true
route = { pattern = "office-days.com/*", zone_name = "office-days.com" }

[[hyperdrive]]
binding = "DB"
id = "2c767ce0fab842108ab723aff8c9d24c"
localConnectionString = "postgresql://PLACEHOLDER:PLACEHOLDER@PLACEHOLDER.supabase.com:6543/postgres"
